### ISSUE TITLE
Can't finish the Android install (step 22)

### ISSUE THREAD

**Issue by ctrai88** [tesla-android/tesla-android.github.io#13]
Hi,
After carefully following the instructions, I'm stuck at step 22 (where the Android should load).

I think that the script doesn't execute. After entering "fastboot reboot" @ step 22, Pi reboots, the I get "Starting kernel..." then screen goes black (for a very long time, I waited like 30-40 minutes.

I don't see anything similar to the screenshot in the guide.

While screen stays black, tried to force restart the Pi (Power cycle). Again - starting kernel, after few seconds black, then nothing.

Tried using Pi4 / 4GB
First try - 32GB SD / Windows
Second try - 32GB SD / Linux

Exact same behaviour

If it helps - tried to execute "fastboot reboot" while in this states, which return black.

Any clue?

root@pve:/home/platform-tools#  ./fastboot devices
100000002c12a466	Android Fastboot

root@pve:/home/platform-tools#  ./fastboot getvar current-slot
current-slot: a
Finished. Total time: 0.000s
root@pve:/home/platform-tools# ./fastboot flash gpt deploy-gpt.img
Sending 'gpt' (128 KB)                             OKAY [  0.018s]
Writing 'gpt'                                      OKAY [  0.096s]
Finished. Total time: 0.203s
root@pve:/home/platform-tools# ./fastboot flash bootloader bootloader-sd.img
Invalid sparse file format at header magic
Sending sparse 'bootloader' 1/1 (9056 KB)          OKAY [  0.616s]
Writing 'bootloader'                               OKAY [ 11.931s]
Finished. Total time: 12.701s
root@pve:/home/platform-tools# ./fastboot flash uboot-env  env.img
Sending 'uboot-env' (256 KB)                       OKAY [  0.022s]
Writing 'uboot-env'                                OKAY [  0.044s]
Finished. Total time: 0.124s
root@pve:/home/platform-tools# ./fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.100s
root@pve:/home/platform-tools#  ./fastboot getvar current-slot
current-slot: a
Finished. Total time: 0.015s
root@pve:/home/platform-tools#  ./fastboot devices
100000002c12a466	Android Fastboot

root@pve:/home/platform-tools#  ./fastboot oem format
OKAY [  0.020s]
Finished. Total time: 0.020s
root@pve:/home/platform-tools#  ./fastboot flash bootloader      bootloader-sd.img
Invalid sparse file format at header magic
Sending sparse 'bootloader' 1/1 (9056 KB)          OKAY [  0.619s]
Writing 'bootloader'                               OKAY [ 11.914s]
Finished. Total time: 12.650s
root@pve:/home/platform-tools# ./fastboot flash uboot-env       env.img
Sending 'uboot-env' (256 KB)                       OKAY [  0.021s]
Writing 'uboot-env'                                OKAY [  0.052s]
Finished. Total time: 0.176s
root@pve:/home/platform-tools# ./fastboot flash recovery_boot   boot.img
Invalid sparse file format at header magic
Sending sparse 'recovery_boot' 1/2 (15332 KB)      OKAY [  1.052s]
Writing 'recovery_boot'                            OKAY [  2.451s]
Sending sparse 'recovery_boot' 2/2 (13740 KB)      OKAY [  0.915s]
Writing 'recovery_boot'                            OKAY [  5.361s]
Finished. Total time: 9.936s
root@pve:/home/platform-tools# ./fastboot flash dtbo_a          boot_dtbo.img
Sending 'dtbo_a' (50 KB)                           OKAY [  0.016s]
Writing 'dtbo_a'                                   OKAY [  0.041s]
Finished. Total time: 0.158s
root@pve:/home/platform-tools# ./fastboot erase misc
Erasing 'misc'                                     OKAY [  0.066s]
Finished. Total time: 0.187s
root@pve:/home/platform-tools#  ./fastboot reboot-fastboot
Rebooting into fastboot                            OKAY [  0.033s]
< waiting for any device >
Finished. Total time: 29.697s
root@pve:/home/platform-tools# ./fastboot flash boot   boot.img
Sending 'boot' (65536 KB)                          OKAY [  1.991s]
Writing 'boot'                                     OKAY [  4.734s]
Finished. Total time: 6.906s
root@pve:/home/platform-tools# ./fastboot flash super  super.img
Invalid sparse file format at header magic
Sending sparse 'super' 1/9 (262140 KB)             OKAY [  8.182s]
Writing 'super'                                    OKAY [ 15.381s]
Sending sparse 'super' 2/9 (262128 KB)             OKAY [  8.146s]
Writing 'super'                                    OKAY [ 15.080s]
Sending sparse 'super' 3/9 (262116 KB)             OKAY [  8.139s]
Writing 'super'                                    OKAY [ 15.420s]
Sending sparse 'super' 4/9 (262128 KB)             OKAY [  8.040s]
Writing 'super'                                    OKAY [ 15.441s]
Sending sparse 'super' 5/9 (262124 KB)             OKAY [  8.159s]
Writing 'super'                                    OKAY [ 15.214s]
Sending sparse 'super' 6/9 (262140 KB)             OKAY [  8.058s]
Writing 'super'                                    OKAY [ 15.627s]
Sending sparse 'super' 7/9 (261616 KB)             OKAY [  8.161s]
Writing 'super'                                    OKAY [ 15.711s]
Sending sparse 'super' 8/9 (262140 KB)             OKAY [  8.070s]
Writing 'super'                                    OKAY [ 15.642s]
Sending sparse 'super' 9/9 (8116 KB)               OKAY [  0.267s]
Writing 'super'                                    OKAY [ 27.242s]
Finished. Total time: 218.621s
root@pve:/home/platform-tools# ./fastboot format:ext4 userdata
Warning: userdata type is raw, but ext4 was requested for formatting.
mke2fs 1.46.2 (28-Feb-2021)
Creating filesystem with 7126139 4k blocks and 1782368 inodes
Filesystem UUID: 71d6491f-876f-4d6a-a007-16fa8dc6974d
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

Sending 'userdata' (180 KB)                        OKAY [  0.020s]
Writing 'userdata'                                 OKAY [  0.044s]
Finished. Total time: 0.222s
root@pve:/home/platform-tools# ./fastboot format:ext4 metadata
Warning: metadata type is raw, but ext4 was requested for formatting.
mke2fs 1.46.2 (28-Feb-2021)
Creating filesystem with 4096 4k blocks and 4096 inodes

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (1024 blocks): done
Writing superblocks and filesystem accounting information: done

Sending 'metadata' (44 KB)                         OKAY [  0.016s]
Writing 'metadata'                                 OKAY [  0.269s]
Finished. Total time: 0.405s
root@pve:/home/platform-tools# ./fastboot reboot
Rebooting                                          OKAY [  0.012s]
Finished. Total time: 0.062s
root@pve:/home/platform-tools# ./fastboot --version
fastboot version 33.0.1-8253317
Installed as /home/platform-tools/fastboot
root@pve:/home/platform-tools# fastboot --version
fastboot version 28.0.2-debian
Installed as /usr/lib/android-sdk/platform-tools/fastboot
root@pve:/home/platform-tools# fastboot --version
fastboot version 28.0.2-debian
Installed as /usr/lib/android-sdk/platform-tools/fastboot
root@pve:/home/platform-tools# 
root@pve:/home/platform-tools# ./fastboot --version
fastboot version 33.0.1-8253317
Installed as /home/platform-tools/fastboot
root@pve:/home/platform-tools#

**Comment by mikegapinski** [comment]
Issue placed in wrong repository
