### ISSUE TITLE
Install instructions do not work. 

### ISSUE THREAD

**Issue by dogzipp** [tesla-android/tesla-android.github.io#15]
Tried two different computers, two different SD cards, and even different USB cables. Results are mixed. There should be a board for people to post and ask for help, or an email. Glad I didn't done before trying it out, since it would have made the frustration worse. 

Maybe a Youtube video tutorial as well of install? Unfortunately everyone's setup is different, and since we're just following a script, we have no idea what the errors mean.

**Comment by mikegapinski** [comment]
try 2022.25.1, setup is simpler + the front end has better error handling for hardware issues
