### ISSUE TITLE
Raspberry PI 400 deply-sd.img?

### ISSUE THREAD

**Issue by derek78w** [tesla-android/tesla-android.github.io#16]
I have a Raspberry PI 400 instead of a Raspberry PI 4 and have deploy-sd.img on the SD card booted to the U-Boot prompt.  However, no matter what I do, I can't find the USB device via Android Debug adb mode under Ubuntu.  Is there any USB device differences that is preventing this?  The terminal output shows that 4 USB device(s) found vs. the 3 in your example screen capture.

**Comment by mikegapinski** [comment]
Sorry, I don't have nor plan to support the Pi 400. If my android base(Glodroid) will start to work on the 400 that will change

**Comment by derek78w** [comment]
Mike, thanks for letting me know.  Is the Pi 400 USB hardware difference causing this?  Do you have a remedy in mind?  Pi 4 stock is out everywhere and I would like to attempt to get this working.
