### ISSUE TITLE
Failed to acquire Android framework ID under Windows.

### ISSUE THREAD

**Issue by st3557** [tesla-android/tesla-android.github.io#18]
Got most part.  I failed for acquire Android framework id.  Got inaccessible or not found error.  Did I miss anything?  Thanks for the help!

**Comment by st3557** [comment]
Thanks for the help!  Sorry.  I am not a programmer, can you give me a little more detail step?

C:\platform-tools>ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]

**Comment by st3557** [comment]
adb root

adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db \

"select * from main where name = \"android_id\";"'

**Comment by elic1973** [comment]
Run this commands one after the other (complete where you 3 dots from the original). 

adb root 

adb shell ‘sqlite3 /data/data….’ 

Select * from main …

**Comment by st3557** [comment]
Thanks for all the help!
I type in this way.  Got inaccessible or not found error.

C:\platform-tools>adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db'
/system/bin/sh: sqlite3 /data/data/com.google.android.gsf/databases/gservices.db: inaccessible or not found

**Comment by earthwormjimwow** [comment]
I encountered the same issues as st3557.  Nothing I typed seemed to work.  Even trying other suggestions online would result in a hex string, but of the wrong length needed.  It's not the android id we need, it's the Google Services Framework Key ID.

What finally worked was side loading this: https://www.apkmirror.com/apk/evozi/device-id/device-id-1-3-2-release/

After booting up the Pi running Android OS, I installed that app, ran it and used the Google Services Framework Key ID it showed.  That worked finally.

**Comment by earthwormjimwow** [comment]
Double click the .apk file within your Android running on your Pi 4.

**Comment by st3557** [comment]
Thanks for the quick response!  When I plug in my usb drive with apk file, I didn't see any movement.  Any format concern for android?

**Comment by earthwormjimwow** [comment]
> Thanks for the quick response! When I plug in my usb drive with apk file, I didn't see any movement. Any format concern for android?

I don't understand what you mean by movement, the drive doesn't show up?  Use FAT32 if you aren't already.

**Comment by earthwormjimwow** [comment]
You could probably also just browse to that URL i posted earlier, in Chrome on your Android Raspberry Pi too, and download it directly.  I didn't do that, so I'm not sure how that website loads on a mobile browser, but it might work fine too.

**Comment by st3557** [comment]
Thanks again!  My usb format is the issue.  I can see the ID now.   Finally, I can proceed further :-D

**Comment by earthwormjimwow** [comment]
Glad you got it working!

**Comment by st3557** [comment]
Hi Earthworm, 

Sorry to bother you again!  I still am a little confused.  Where we actually connect the usb lte stick.  Is it on the windows computer or Android Pi.  I feel I am very close, but not quite there yet.   Here is my configuration.  Android Pi I use Raspberry Pi 4, Linux Pi I use Raspberry 3b.

Thanks again!

**Comment by earthwormjimwow** [comment]
The stick would plug into the Linux Pi, since it needs an internet connection in order for the Tesla to accept its wifi hot spot.

The Linux Pi is essentially your router.

**Comment by st3557** [comment]
I see. I purchased this usb lte stick from ebay: https://www.ebay.com/itm/324292600049?mkcid=16&mkevt=1&mkrid=711-127632-2357-0&ssspo=kfRlFGkNSSO&sssrc=2047675&ssuid&widget_ver=artemis&media=COPY
And I use U.S. T mobile SIM card.

Any setup need to do on the stick 192.168.1.1 site?  Look like this stick is not a "hot spot".  Do we need to setup SSID?   

Thanks again.

**Comment by earthwormjimwow** [comment]
The stick is just acting as a modem to the Linux Pi, the Linux Pi _is_ your hotspot.  You already setup the SSID if you followed the directions for the Linux Pi setup.  That's the SSID your car connects to, the one the Linux Pi is broadcasting.

**Comment by st3557** [comment]
Make sense.  My Tesla-Android wifi is up now.  One last thing is to figure out the Android Pi's mac address.  For some reason, My monitor lost signal to the Android Pi.  Weird.  Hate to re-do it again.

Thanks again!

**Comment by st3557** [comment]
Big thanks to earthworm!!!  Finally, it is work now on my Y.    Any word when will we receive the 2nd Alpha test build?  According to the Video.  It will have audio for navigation.  The only thing that I didn't do is over clock setting.  Don't know how to put it in the configuration file though adb terminal. So far I use 948X738 resolution at 30 fps seems workable.
