### ISSUE TITLE
Device not detecting Carlinkit adapter

### ISSUE THREAD

**Issue by legochris** [tesla-android/tesla-android.github.io#19]
I have completed the setup instructions as described, and am successfully able to navigate the Android interface through my touchscreen device. However, when I launch the AutoKit app, I get a screen instructing me to "Please insert the product". I have tried plugging the Carlinkit adapter into all 4 USB-A ports on the Pi running Android, yet am still stuck at this message. Am I missing any settings that need to be configured for the Pi to detect the adapter?

**Comment by legochris** [comment]
I was able to connect the Carlinkit adapter to a separate Android tablet and the AutoKit app was able to recognize the device, so I don't think the adapter is the issue. Any suggestions for how to debug why the device is not being seen on the Pi?

**Comment by mikegapinski** [comment]
Check the power supply

**Comment by hasselboxster** [comment]
thanks for this information, helped me too
