### ISSUE TITLE
Confusion around 2022.25.1 documentation

### ISSUE THREAD

**Issue by anuragphadke** [tesla-android/tesla-android.github.io#28]
Hi,
Can someone help clarify the following documentation:

1. Configure your USB LTE stick using your computer. No other setup then saving your PIN is required. Verify if Internet is accessible after unpluging and pluging your device back into your computer. Then, connect your USB LTE stick to your Pi that will be used for the Linux system.
2. Connect the HDMI capture interface to the camera header on your Pi.
3. Connect the capture interface with a second Pi using an microHDMI to HDMI cable.
4. Using an Ethernet cable connect both your boards together.
5. Plug your Linux Pi to a power source.
6. Wait a few minutes for the Linux Pi to boot up for the first time.
7. Connect your computer to Tesla Android Wi-Fi network. The default password is: “changeit”
8. Using a Terminal of your choice connect to your Linux Pi using SSH:
ssh pi@3.3.3.1

Questions:
For item 4, is it a special cable or just regular cable?
For item 8, how does the `pi` connect to ethernet? AFAIK, the LinuxPi and AndroidPi are connected via Ethernet, but how does the LinuxPi get an IP? Doe LinuxPi boot up and broadcast this network name?

Lastly, do I need to connect LinuxPi to any external display for the setup?

**Comment by anuragphadke** [comment]
self closing:
For item 4, is it a special cable or just regular cable?
Yes, regular cable.

For item 8, how does the pi connect to ethernet? AFAIK, the LinuxPi and AndroidPi are connected via Ethernet, but how does the LinuxPi get an IP? Doe LinuxPi boot up and broadcast this network name?
LinuxPi boots up and broadcasts this network.

Lastly, do I need to connect LinuxPi to any external display for the setup?
Not needed.

**Comment by hughker** [comment]
Did you RTFD?
