### ISSUE TITLE
Cannot write deploy-sd properly to SD Card

### ISSUE THREAD

**Issue by mbhforum** [tesla-android/tesla-android.github.io#3]
Trying balenaEtcher or Rpi Etcher, both produced errors about unable to read the SD card when the flashing is complete.  The operation still reports successful in the flashing app.  When trying to boot a Rpi 4 with the SD Card, you get Boot Loader Image errors saying "Boot Image Header is Incorrect"  I flashed the card with the Rpi OS and it worked fine, so it's not my MacOS desktop or the SD Card.  I also tried a different MacOS and same issue happens there.

**Comment by mikegapinski** [comment]
Please use the issue tracker/discussion board https://github.com/tesla-android/issue-tracker
