### ISSUE TITLE
Tesla is unable to obtain an IP address

### ISSUE THREAD

**Issue by soothslayer** [tesla-android/tesla-android.github.io#36]
When I don't use an Internet dongle my Tesla refuses to connect to wifi. Stating either "unable to obtain an IP address" or that the connection is presenting a splash screen/consent page that isn't supported.

**Comment by soothslayer** [comment]
I’m running the latest (2022.27.1). The problem was something to do with using a raspberry pi zero w instead of a 3. The zero w worked with the initial release (2022.25.1) after running “sudo pihole -up” to update pihole and get dhcp working. But that didn’t resolve the dhcp issue (or the splash screen/consent screen error on the latest build) on subsequent newer builds. 

Once I upgraded from a raspberry pi zero to a 4 the issue went away.

**Comment by marcdubois71450** [comment]
Hello, in fact the tesla refuses to connect a wifi network that does not have internet access.  And for that it displays a DHCP error.  It's probably an internet access problem and not a DHCP problem.

**Comment by mikegapinski** [comment]
Tesla Android has an offline mode that bypasses that, there was an issue for the Chinese market that I've resolved for the next update
