### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by lccreech** [tesla-android/tesla-android.github.io#38]
Line 15 " fastboot reboot-fastboot " is not a valid command.
It should be " fastboot reboot-bootloader "
"

**Comment by lccreech** [comment]
fastboot format:ext4 userdata
FAILED (remote: failed to set partition)

fastboot format:ext4 metadata
mke2fs 1.45.5 (07-Jan-2020)
/tmp/TemporaryFile-WX1yka: Unimplemented ext2 library function while setting up superblock
/usr/lib/android-sdk/platform-tools/mke2fs failed with status 1
mke2fs failed: 1
error: Cannot generate image for metadata

fastboot devices
10000000d9be3f62	fastboot

**Comment by mikegapinski** [comment]
The commands are valid. Please use a current version of fastboot
