### ISSUE TITLE
MacOS not detecting fastboot device

### ISSUE THREAD

**Issue by gSPK99** [tesla-android/tesla-android.github.io#46]
I am trying to create the tesla-android project.  i have had no problems until i get to step 6.

Verify that your computer has detected the Pi by typing: “fastboot devices”. Example of a correct output: 

at this point it does not detect the Pi.

i am unsure where to go from here.  I am on a MacBook 14 Monterey

**Comment by soothslayer** [comment]
Installing android studio sdk resolved the issue for me. After installing, my raspberry pi was detected.

**Comment by gSPK99** [comment]
i installed it this morning ... however, still no luck :(
but thank you for the quick response

**Comment by gSPK99** [comment]
OK I started from scratch I went to An old windows machine. 

I was able to get it up and running thanks to everyone for their help

**Comment by gSPK99** [comment]
However I have a new issue, once deployed to the Tesla I get a ” could not connect to network unable to obtain  IP address please check DHCP server settings.

**Comment by gSPK99** [comment]
![Uploading EF86A609-7962-4BB0-8271-EDDAE748FCDC.jpeg…]()

**Comment by gSPK99** [comment]
Closing the issue of fastboot device on MacOS as i completed this on a windows machine
