### ISSUE TITLE
Hardware Requirements: Pi Zero 2 W ok?

### ISSUE THREAD

**Issue by cariacou** [tesla-android/tesla-android.github.io#48]
I saw the list of hardware requirements, and suggestion for the 4GB of ram. 
Is this still current? 

The other tesla CarPlay project on GitHub seems to work on a Pi Zero 2 W (512MB of ram)

**Comment by soothslayer** [comment]
I ran in to DHCP issues when I tried 2022.27.1 on a raspberry pi zero 2 W. I have it running on an overclocked raspberry pi 4 8GB and its still sluggish so I don't suspect 512 mb will be enough.

**Comment by mikegapinski** [comment]
Other projects just forward the image from the Carlinkit dongle, I run a full Android system. It's not going to work on a Zero 2 W, but the performance of the single board stack will improve a lot in next updates after the csi 2 hdmi is dropped. It's limited by the software right now, not the hardware
