### ISSUE TITLE
Telsa Cannot connect to Pi

### ISSUE THREAD

**Issue by gSPK99** [tesla-android/tesla-android.github.io#53]
Deployed to the Tesla Model S 2018 
I get a ” could not connect to network unable to obtain IP address please check DHCP server settings."
If i use my phone within the car it connects no problem.

any help would be great

**Comment by mikegapinski** [comment]
<img width="418" alt="image" src="https://user-images.githubusercontent.com/930055/196036818-61fb6514-07cf-41b6-b612-a74565933188.png">
