### ISSUE TITLE
is this project possible to run via Odroid N2+? 

### ISSUE THREAD

**Issue by aronlocsei** [tesla-android/tesla-android.github.io#54]
Hello, 
I am curios if this project was somehow possible with an Odroid N2+ (wifi+bluetooth dongle) => or having a raspberry Pi 4 is a must? I'm currently running Android 9 on it, and i have success setting up the Carlin carkit -> currently running to my monitor via HDMI. was curious if there was a way to "hack it" from this starting point to have the solution also work in my Tesla. Thanks for any input!

**Comment by mikegapinski** [comment]
Only Raspberry Pi 4 is supported, I do not expect that to change anytime soon
