### ISSUE TITLE
Tesla Android 2022.44.1 results in DHCP time out and unreachable internet on FSD 10.69.2.3 (2022.20.8)

### ISSUE THREAD

**Issue by thisLambo** [tesla-android/tesla-android.github.io#59]
When trying to connect to the hotspot the following messages were observed;
“The internet is unreachable. Please check your firewall settings and internet configuration”

“Unable to obtain IP address. Please check DHCP server settings”

I am currently running FSD 10.69.2.3 (2022.20.8)

**Comment by thisLambo** [comment]
![B02DEF1F-5407-4BC5-AD56-0505A8E8900A](https://user-images.githubusercontent.com/10174763/199173579-3d15ba11-d566-4ec8-9d0e-8d755f1095c3.jpeg)
![E5F6B00E-B113-43E5-BC43-1C4E5B094221](https://user-images.githubusercontent.com/10174763/199173589-82f8593f-3aaa-47d4-84b1-b24e73095ae6.jpeg)
![C8890D3A-EB81-44A0-B649-CDC8C6D71E11](https://user-images.githubusercontent.com/10174763/199173593-6783878b-06cc-44ab-b1cd-23d030978f08.jpeg)

**Comment by thisLambo** [comment]
![25C494AA-93D2-463A-A554-D41A49F433D5](https://user-images.githubusercontent.com/10174763/199173935-30980e31-435e-477e-a363-afb804bf7a0e.jpeg)
![B2FC8BBB-AAD1-407E-B8B5-E9DAA8857857](https://user-images.githubusercontent.com/10174763/199173937-dc16447c-c512-47f5-8bf6-f5fe14f3b32b.jpeg)
![BFB1745C-A11C-4A22-9851-31A9D28DFD2D](https://user-images.githubusercontent.com/10174763/199173938-a75d1d67-743a-4f31-9363-44624b5232d2.jpeg)

**Comment by mikegapinski** [comment]
2022.44.2 on the way, forgot to include one file in the image.
